### ISSUE TITLE
Problems related to multithreaded access imposed by Godot

### ISSUE THREAD

**Issue by Bromeon** [godot-rust/gdext#713]
There are several issues related to thread-ID checks that currently require either `experimental-threads` feature, or don't work at all. This issue tracks those.

- [x] https://github.com/godot-rust/gdext/issues/556
- [ ] https://github.com/godot-rust/gdext/issues/597
- [ ] https://github.com/godot-rust/gdext/issues/610
- [x] https://github.com/godot-rust/gdext/issues/709
- [ ] https://github.com/godot-rust/gdext/issues/938
- [ ] https://github.com/godot-rust/gdext/issues/1427
- [ ] C# finalizers run into panics as they run on separate thread ([Discord](https://discord.com/channels/723850269347283004/1430885218419474455/1430885218419474455))
- [ ] Some virtual methods use `&self` which happens to be nicer for multithreading, but worse for single-threading ergonomics ([Discord](https://discord.com/channels/723850269347283004/1454764658375393441/1454764658375393441))
